version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - ${MAIN_PORT}:80
        volumes:
            - .:/var/www/
            # - ./docker_configs/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_EXT_PORT}:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./database/msl_db.sql:/docker-entrypoint-initdb.d/start.sql

    # adminer:
    # image: adminer
    # restart: always
    # ports:
    # - 8080:8080

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    mysql-data:
